### ISSUE TITLE
mvn install时报错

### ISSUE THREAD

**Issue by Ashsora** [platonai/PulsarRPA#53]
我用的ubuntu 22.04，maven 3.9.6， java 19.0.2。
在下载后的文件根目录里用mvn install 上传项目，中间一直报错，调了蛮久都没解决。
报错如图：
![2023-12-21_17-42](https://github.com/platonai/PulsarRPA/assets/55279988/630d2b5b-874d-41e4-a315-8ae6580366fa)
![2023-12-21_17-41](https://github.com/platonai/PulsarRPA/assets/55279988/fadef7b8-64f9-4557-9841-7f0ff756a672)
![2023-12-21_17-41_1](https://github.com/platonai/PulsarRPA/assets/55279988/de5a21a8-fe35-4880-8200-6f93dfdde02e)

请问可能是什么原因？我之前是maven 3.6，报错后按照issues里的说的更新maven后依然报错。kotlin编译器也安装好了，有没有可能是缺少了什么组件？

**Comment by galaxyeye** [comment]
Try JDK-11.

**Comment by Ashsora** [comment]
> Try JDK-11.
切换到jdk11依然报错，还是相同的错误。我注意到上面出现了这样的报错
![2023-12-26_17-32_1](https://github.com/platonai/PulsarRPA/assets/55279988/c13af11b-f5d8-46b7-8503-1dbf5168a764)
![2023-12-26_17-32](https://github.com/platonai/PulsarRPA/assets/55279988/6f8912c6-fff2-4786-8f19-12434163b26e)
有没有可能是由于源码不完整？又或者是kotlin版本的问题？请贴上你们所用的kotlin版本作为参考
