### ISSUE TITLE
启动REST服务时报错

### ISSUE THREAD

**Issue by Aaronx-Gallagher** [platonai/PulsarRPA#54]
环境：windows11 ，jdk11，maven 3.6.3       /      centos7   jdk11  maven3.9.2  两套系统
将代码gitclone到本地后，启动rest服务报错
![issue](https://github.com/platonai/PulsarRPA/assets/126217889/9c2f7d07-ed65-4c1f-9e77-d6f7a3b1d2f0)

但是windows11的项目在idea中可以正常运行pulsar-app/pulsar-examples/里面的例子。
centos7按照文档上bin/build-run.sh也是报这个错误。
将版本换成1.10.22也报这个错误。
请问是怎么回事。

**Comment by Aaronx-Gallagher** [comment]
是有什么配置需要配吗？我是按照readme里面的gitclone以后直接进行的bin/build-run.sh

**Comment by Aaronx-Gallagher** [comment]
找到了报错的地点：ProxyPoolManagerFactory.kt文件中的
private fun computeIfAbsent(conf: ImmutableConfig): ProxyPoolManager {
        synchronized(ProxyPoolManagerFactory::class) {
            val clazz = getClass(conf)
            return proxyPoolManagers.computeIfAbsent(clazz.name) {
                clazz.constructors.first { it.parameters.size == 2 }.newInstance(proxyPool, conf) as ProxyPoolManager
            }
        }
    }
里面 it.parameters.size == 2的判断有问题导致出现此问题

**Comment by galaxyeye** [comment]
Will be fixed on 1.10.24.

**Comment by galaxyeye** [comment]
You can run PulsarRPAPro to experience better REST services.
