### ISSUE TITLE
ebay  'web xSql' not result 

### ISSUE THREAD

**Issue by pljay** [platonai/PulsarRPA#55]
url:**https://www.ebay.com/itm/155607414510**
![image](https://github.com/platonai/PulsarRPA/assets/35439240/a6d19b47-6473-4766-9f3d-6f89af45ceba)

**Comment by pljay** [comment]
![image](https://github.com/platonai/PulsarRPA/assets/35439240/ad1d2205-2ea1-4bf0-84f3-338130fab5ee)

**Comment by galaxyeye** [comment]
Please paste the X-SQL in text format.

**Comment by pljay** [comment]
select
                dom_base_uri(dom) as `url`,
                dom_first_text(dom, '.main-container #mainContent [class~='x-item-title'] .x-item-title__mainTitle') as `title`,
                dom_first_text(dom, '.main-container #mainContent [class~='x-price-section'] .x-price-primary') as `defaultPrice`
from        load_and_select('URL' , ':root');

**Comment by pljay** [comment]
> Please paste the X-SQL in text format.

select
dom_base_uri(dom) as url,
dom_first_text(dom, '.main-container #mainContent [class~='x-item-title'] .x-item-title__mainTitle') as title,
dom_first_text(dom, '.main-container #mainContent [class~='x-price-section'] .x-price-primary') as defaultPrice
from load_and_select('URL' , ':root');

**Comment by platonai** [comment]
The SQL looks correct. But I need more information to find out what happened. You can check your log for more information, if you can not resolve the problem yourself, please upload the log file.
