### ISSUE TITLE
target包是缺少吗还是我的版本下载的不对  用的是master分支

### ISSUE THREAD

**Issue by lax0306** [platonai/PulsarRPA#57]
![image](https://github.com/platonai/PulsarRPA/assets/40849111/7857607f-3f04-4e25-9318-4cc155c6a2c9)
其他分支也看了  也没有这个包及文件

**Comment by platonai** [comment]
Add the following lines to your .gitignore:

```
# a source directory is "target"
!*/**/src/main/java/com/github/kklisura/cdt/protocol/v2023/types/target
!*/**/src/**/target
```

The lines exist by default, check if you have overwritten the file.
