### ISSUE TITLE
大佬，代码有暴露设置浏览器exe路径的接口吗？

### ISSUE THREAD

**Issue by ZhujingJava** [platonai/PulsarRPA#58]
我找了一圈代码，没有找到设置浏览器路径的接口，通过system.setproperty()也不起作用，现在打开浏览器就会自动更新到122版本，降级到104就没问问题，

**Comment by ZhujingJava** [comment]
找到了onWillLaunchBrowser这个方法，但是没有找到设置的接口

**Comment by platonai** [comment]
System.setProperty(CapabilityTypes.BROWSER_CHROME_PATH, "your-chrome-home");

See https://github.com/platonai/PulsarRPA/issues/9

Or, check the code for detail: https://github.com/platonai/PulsarRPA/blob/461c487f6a22164ef858bd07c012f5102478a5ee/pulsar-common/src/main/kotlin/ai/platon/pulsar/common/browser/Browsers.kt

**Comment by ZhujingJava** [comment]
好的，抱歉，是我不够心细，没有读完源代码，sorry
